function df_p_q_gamma_ = df_p_q_gamma(in1,in2,in3)
%DF_P_Q_GAMMA
%    DF_P_Q_GAMMA_ = DF_P_Q_GAMMA(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:02

g3 = in1(3,:);
theta = in3(3,:);
wl = in2(2,:);
wr = in2(1,:);
t2 = cos(theta);
t3 = sin(theta);
df_p_q_gamma_ = reshape([-g3.*((t3.*wl)./2.0+(t3.*wr)./2.0),g3.*((t2.*wl)./2.0+(t2.*wr)./2.0),0.0,0.0,0.0,0.0],[3,2]);
end
