function df_p_u_uai_ = df_p_u_uai(in1,in2,in3)
%DF_P_U_UAI
%    DF_P_U_UAI_ = DF_P_U_UAI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:03

b = in3(2,:);
r = in3(1,:);
theta = in2(3,:);
u_ai1 = in1(1,:);
u_ai2 = in1(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
t5 = t4.^2;
df_p_u_uai_ = reshape([(t2.*u_ai1)./2.0+(t2.*u_ai2)./2.0,(t3.*u_ai1)./2.0+(t3.*u_ai2)./2.0,(t4.*u_ai1)./2.0-(t4.*u_ai2)./2.0,0.0,0.0,r.*t5.*u_ai1.*(-1.0./2.0)+(r.*t5.*u_ai2)./2.0],[3,2]);
end
