function df_q_q_gamma_ = df_q_q_gamma(in1,in2,in3,in4)
%DF_Q_Q_GAMMA
%    DF_Q_Q_GAMMA_ = DF_Q_Q_GAMMA(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:02

g3 = in1(3,:);
r = in2(1,:);
theta = in4(3,:);
wl = in3(2,:);
wr = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
df_q_q_gamma_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-g3.*((r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0),-g3.*((r.*t3.*wl)./2.0+(r.*t3.*wr)./2.0),0.0],[3,3]);
end
