function df_q_u_uai_ = df_q_u_uai(in1,in2,in3)
%DF_Q_U_UAI
%    DF_Q_U_UAI_ = DF_Q_U_UAI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:02

r = in3(1,:);
theta = in1(3,:);
u_ai1 = in2(1,:);
u_ai2 = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
df_q_u_uai_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,r.*t3.*u_ai1.*(-1.0./2.0)-(r.*t3.*u_ai2)./2.0,(r.*t2.*u_ai1)./2.0+(r.*t2.*u_ai2)./2.0,0.0],[3,3]);
end
