function df_u_q_gamma_ = df_u_q_gamma(in1,in2,in3)
%DF_U_Q_GAMMA
%    DF_U_Q_GAMMA_ = DF_U_Q_GAMMA(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:03

g3 = in1(3,:);
r = in2(1,:);
theta = in3(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = (g3.*r.*t2)./2.0;
t5 = (g3.*r.*t3)./2.0;
t6 = -t5;
df_u_q_gamma_ = reshape([t6,t4,0.0,t6,t4,0.0],[3,2]);
end
