function dg_xhi_q_gamma_ = dg_xhi_q_gamma(in1,in2,k_v,k_i,k_p)
%DG_XHI_Q_GAMMA
%    DG_XHI_Q_GAMMA_ = DG_XHI_Q_GAMMA(IN1,IN2,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:05

g3 = in1(3,:);
theta = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
dg_xhi_q_gamma_ = reshape([0.0,0.0,0.0,-g3.*k_i.*t3.*t7,0.0,0.0,g3.*k_i.*t2.*t7,0.0,0.0],[3,3]);
end
