function dg_xhi_xhi_gammaxhi_ = dg_xhi_xhi_gammaxhi
%DG_XHI_XHI_GAMMAXHI
%    DG_XHI_XHI_GAMMAXHI_ = DG_XHI_XHI_GAMMAXHI

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:50

dg_xhi_xhi_gammaxhi_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
