function func = dgq_a5y(k_p,theta)
%DGQ_A5Y
%    FUNC = DGQ_A5Y(K_P,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:53

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(k_p.*t2)./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
