function func = dgq_a2x(k_p,k_v,t,theta)
%DGQ_A2X
%    FUNC = DGQ_A2X(K_P,K_V,T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:58

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*6.0+k_p.*t.^3+k_v.*t.^2.*3.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
