function func = dgq_a5x(k_p,theta)
%DGQ_A5X
%    FUNC = DGQ_A5X(K_P,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:59

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(k_p.*t2)./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
