function func = dgq_a4y(k_p,k_v,t,theta)
%DGQ_A4Y
%    FUNC = DGQ_A4Y(K_P,K_V,T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:50

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*(k_v+k_p.*t))./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
