function func = dgxhi_a1x
%DGXHI_A1X
%    FUNC = DGXHI_A1X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:09:00

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
