function func = dgxhi_a2y
%DGXHI_A2Y
%    FUNC = DGXHI_A2Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:09:01

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
