function func = dgxhi_a2y
%DGXHI_A2Y
%    FUNC = DGXHI_A2Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:54

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
