function func = dgxhi_a5y
%DGXHI_A5Y
%    FUNC = DGXHI_A5Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:09:02

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
