function dh_q_q_gamma_ = dh_q_q_gamma(in1,in2,in3,in4,in5,in6,in7,k_v,k_i,k_p)
%DH_Q_Q_GAMMA
%    DH_Q_Q_GAMMA_ = DH_Q_Q_GAMMA(IN1,IN2,IN3,IN4,IN5,IN6,IN7,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:03

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = k_i.*xhi_x;
t5 = k_i.*xhi_y;
t10 = 1.0./r;
t11 = -x_d;
t12 = -y_d;
t6 = t2.^2;
t7 = t3.^2;
t8 = t2.*xhi_v;
t9 = t3.*xhi_v;
t15 = t11+x;
t17 = t12+y;
t13 = t6.*xhi_v;
t14 = t7.*xhi_v;
t16 = -t8;
t18 = -t9;
t20 = k_p.*t15;
t21 = k_p.*t17;
t19 = dx_d+t16;
t22 = dy_d+t18;
t25 = -t20;
t26 = -t21;
t27 = t13+t14;
t23 = k_v.*t19;
t24 = k_v.*t22;
t28 = 1.0./t27;
t29 = ddx_d+t4+t23+t25;
t30 = ddy_d+t5+t24+t26;
t31 = b.*g1.*k_p.*t2.*t10.*t28;
t32 = b.*g3.*k_p.*t2.*t10.*t28;
t33 = b.*g2.*k_p.*t3.*t10.*t28;
t34 = b.*g3.*k_p.*t3.*t10.*t28;
t35 = t3.*t28.*t29;
t36 = t2.*t28.*t30;
t37 = -t36;
t38 = t35+t37;
t39 = b.*g3.*t10.*t38;
dh_q_q_gamma_ = reshape([t32,-t32,t34,-t34,t31+t33+t39,-t31-t33-t39],[2,3]);
end
