function func = dhq_a1y(b,k_p,k_v,r,t,theta,xhi_v)
%DHQ_A1Y
%    FUNC = DHQ_A1Y(B,K_P,K_V,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:25

t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t5 = t.^3;
t9 = 1.0./r;
t6 = t4.^2;
t7 = t2.^2;
t8 = t3.^2;
t13 = t4.*1.2e+1;
t14 = k_v.*t5.*4.0;
t10 = k_p.*t6;
t11 = t7.*xhi_v;
t12 = t8.*xhi_v;
t15 = t11+t12;
t17 = t10+t13+t14;
t16 = 1.0./t15;
t18 = b.*t3.*t9.*t16.*t17;
func = reshape([0.0,0.0,0.0,0.0,-t18,t18],[2,3]);
end
