function func = dhq_a4y(b,k_p,k_v,r,t,theta,xhi_v)
%DHQ_A4Y
%    FUNC = DHQ_A4Y(B,K_P,K_V,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:26

t2 = cos(theta);
t3 = sin(theta);
t4 = k_p.*t;
t7 = 1.0./r;
t5 = t2.^2;
t6 = t3.^2;
t8 = k_v+t4;
t9 = t5.*xhi_v;
t10 = t6.*xhi_v;
t11 = t9+t10;
t12 = 1.0./t11;
t13 = b.*t3.*t7.*t8.*t12;
func = reshape([0.0,0.0,0.0,0.0,-t13,t13],[2,3]);
end
