function func = dhq_a5y(b,k_p,r,theta,xhi_v)
%DHQ_A5Y
%    FUNC = DHQ_A5Y(B,K_P,R,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:55

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4.*xhi_v;
t8 = t5.*xhi_v;
t9 = t7+t8;
t10 = 1.0./t9;
t11 = b.*k_p.*t3.*t6.*t10;
func = reshape([0.0,0.0,0.0,0.0,-t11,t11],[2,3]);
end
