function func = dhxhi_a5y(b,k_p,r,theta,xhi_v)
%DHXHI_A5Y
%    FUNC = DHXHI_A5Y(B,K_P,R,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:58

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4.*xhi_v;
t8 = t5.*xhi_v;
t9 = t4+t5;
t10 = t7+t8;
t11 = 1.0./t10.^2;
t12 = b.*k_p.*t2.*t6.*t9.*t11;
func = reshape([-t12,t12,0.0,0.0,0.0,0.0],[2,3]);
end
