function func = dhxhi_a3y(b,k_p,k_v,r,t,theta,xhi_v)
%DHXHI_A3Y
%    FUNC = DHXHI_A3Y(B,K_P,K_V,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:57

t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t6 = k_v.*t.*2.0;
t8 = 1.0./r;
t5 = t2.^2;
t7 = t3.^2;
t9 = k_p.*t4;
t10 = t5.*xhi_v;
t11 = t7.*xhi_v;
t12 = t5+t7;
t13 = t6+t9+2.0;
t14 = t10+t11;
t15 = 1.0./t14.^2;
t16 = b.*t2.*t8.*t12.*t13.*t15;
func = reshape([-t16,t16,0.0,0.0,0.0,0.0],[2,3]);
end
