function func = dhxhi_a1x(b,k_p,k_v,r,t,theta,xhi_v)
%DHXHI_A1X
%    FUNC = DHXHI_A1X(B,K_P,K_V,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:27

t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t5 = t.^3;
t9 = 1.0./r;
t6 = t4.^2;
t7 = t2.^2;
t8 = t3.^2;
t13 = t4.*1.2e+1;
t14 = k_v.*t5.*4.0;
t10 = k_p.*t6;
t11 = t7.*xhi_v;
t12 = t8.*xhi_v;
t15 = t7+t8;
t16 = t11+t12;
t18 = t10+t13+t14;
t17 = 1.0./t16.^2;
t19 = b.*t3.*t9.*t15.*t17.*t18;
func = reshape([t19,-t19,0.0,0.0,0.0,0.0],[2,3]);
end
