function f_u = ff_u(in1,in2)
%FF_U
%    F_U = FF_U(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:31:52

b = in2(2,:);
r = in2(1,:);
theta = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
t5 = (r.*t2)./2.0;
t6 = (r.*t3)./2.0;
t7 = (r.*t4)./2.0;
f_u = reshape([t5,t6,t7,t5,t6,-t7],[3,2]);
end
