function g_q = fg_q(in1,in2,in3,in4,in5,k_v,k_i,k_p)
%FG_Q
%    G_Q = FG_Q(IN1,IN2,IN3,IN4,IN5,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:45

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
g_q = reshape([-k_p.*t2.*t7,-1.0,0.0,-k_p.*t3.*t7,0.0,-1.0,-t3.*t7.*(ddx_d+k_i.*xhi_x-k_p.*(x-x_d)+k_v.*(dx_d-t2.*xhi_v))+t2.*t7.*(ddy_d+k_i.*xhi_y-k_p.*(y-y_d)+k_v.*(dy_d-t3.*xhi_v)),0.0,0.0],[3,3]);
end
