function g_xhi = fg_xhi(in1,k_v,k_i,k_p)
%FG_XHI
%    G_XHI = FG_XHI(IN1,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:31:54

theta = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
g_xhi = reshape([-k_v.*t4.*t7-k_v.*t5.*t7,0.0,0.0,k_i.*t2.*t7,0.0,0.0,k_i.*t3.*t7,0.0,0.0],[3,3]);
end
