function h_q = fh_q(in1,in2,in3,in4,in5,in6,k_v,k_i,k_p)
%FH_Q
%    H_Q = FH_Q(IN1,IN2,IN3,IN4,IN5,IN6,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:31:53

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = k_i.*xhi_x;
t5 = k_i.*xhi_y;
t10 = 1.0./r;
t11 = -x_d;
t12 = -y_d;
t6 = t2.^2;
t7 = t3.^2;
t8 = t2.*xhi_v;
t9 = t3.*xhi_v;
t15 = t11+x;
t17 = t12+y;
t13 = t6.*xhi_v;
t14 = t7.*xhi_v;
t16 = -t8;
t18 = -t9;
t20 = k_p.*t15;
t21 = k_p.*t17;
t19 = dx_d+t16;
t22 = dy_d+t18;
t25 = -t20;
t26 = -t21;
t27 = t13+t14;
t23 = k_v.*t19;
t24 = k_v.*t22;
t28 = 1.0./t27;
t29 = k_v.*t13.*t28;
t30 = k_v.*t14.*t28;
t31 = ddx_d+t4+t23+t25;
t32 = b.*k_p.*t2.*t10.*t28;
t33 = ddy_d+t5+t24+t26;
t34 = b.*k_p.*t3.*t10.*t28;
t35 = t3.*t28.*t33;
t36 = t2.*t28.*t31;
t37 = t29+t30+t35+t36;
t38 = b.*t10.*t37;
h_q = reshape([t34,-t34,-t32,t32,-t38,t38],[2,3]);
end
