function g_a_5y_ = g_a_5y(in1,k_p)
%G_A_5Y
%    G_A_5Y_ = G_A_5Y(IN1,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:53

theta = in1(3,:);
t2 = sin(theta);
g_a_5y_ = [(k_p.*t2)./(cos(theta).^2+t2.^2);0.0;1.0];
end
