function g_a_4x_ = g_a_4x(in1,t,k_v,k_p)
%G_A_4X
%    G_A_4X_ = G_A_4X(IN1,T,K_V,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:53

theta = in1(3,:);
t2 = cos(theta);
g_a_4x_ = [(t2.*(k_v+k_p.*t))./(sin(theta).^2+t2.^2);t;0.0];
end
