function g_a_1y_ = g_a_1y(in1,t,k_v,k_p)
%G_A_1Y
%    G_A_1Y_ = G_A_1Y(IN1,T,K_V,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:52

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^4;
g_a_1y_ = [(t2.*(k_p.*t3+k_v.*t.^3.*4.0+t.^2.*1.2e+1))./(cos(theta).^2+t2.^2);0.0;t3];
end
