function g_a_1x_ = g_a_1x(in1,t,k_v,k_p)
%G_A_1X
%    G_A_1X_ = G_A_1X(IN1,T,K_V,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2023 17:32:20

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^4;
g_a_1x_ = [(t2.*(k_p.*t3+k_v.*t.^3.*4.0+t.^2.*1.2e+1))./(sin(theta).^2+t2.^2);t3;0.0];
end
