function h_a_4x_ = h_a_4x(in1,t,in3,in4,k_v,k_p)
%H_A_4X
%    H_A_4X_ = H_A_4X(IN1,T,IN3,IN4,K_V,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:52

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = k_p.*t;
t7 = 1.0./r;
t5 = t2.^2;
t6 = t3.^2;
t8 = k_v+t4;
t9 = t5.*xhi_v;
t10 = t6.*xhi_v;
t11 = t9+t10;
t12 = 1.0./t11;
t13 = b.*t3.*t7.*t8.*t12;
h_a_4x_ = [-t13;t13];
end
