function new_u = new_u(in1,in2,in3,in4,in5,in6,k_v,k_i,k_p)
%NEW_U
%    NEW_U = NEW_U(IN1,IN2,IN3,IN4,IN5,IN6,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:44

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = k_i.*xhi_x;
t5 = k_i.*xhi_y;
t10 = 1.0./r;
t11 = -x_d;
t12 = -y_d;
t6 = t2.^2;
t7 = t3.^2;
t8 = t2.*xhi_v;
t9 = t3.*xhi_v;
t15 = t10.*xhi_v;
t16 = t11+x;
t18 = t12+y;
t13 = t6.*xhi_v;
t14 = t7.*xhi_v;
t17 = -t8;
t19 = -t9;
t21 = k_p.*t16;
t22 = k_p.*t18;
t20 = dx_d+t17;
t23 = dy_d+t19;
t26 = -t21;
t27 = -t22;
t28 = t13+t14;
t24 = k_v.*t20;
t25 = k_v.*t23;
t29 = 1.0./t28;
t30 = ddx_d+t4+t24+t26;
t31 = ddy_d+t5+t25+t27;
t32 = t3.*t29.*t30;
t33 = t2.*t29.*t31;
t34 = -t33;
t35 = t32+t34;
t36 = b.*t10.*t35;
new_u = [t15-t36;t15+t36];
end
