function q_dot = q_dot(in1,in2,in3,k_v,k_i,k_p)
%Q_DOT
%    Q_DOT = Q_DOT(IN1,IN2,IN3,K_V,K_I,K_P)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-May-2023 12:08:43

b = in3(2,:);
r = in3(1,:);
theta = in1(3,:);
wl = in2(2,:);
wr = in2(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
q_dot = [(r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0;(r.*t3.*wl)./2.0+(r.*t3.*wr)./2.0;r.*t4.*wl.*(-1.0./2.0)+(r.*t4.*wr)./2.0];
end
